InternetStoreViewer/Controllers/SiteController.cs
using InternetStoreViewer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace InternetStoreViewer.Controllers
{
    public class SiteController : Controller
    {
        private ViewerRepositoryAsync<SiteUrl> _sitesRepo;

        public SiteController()
        {
            _sitesRepo = new ViewerRepositoryAsync<SiteUrl>();
        }

        public SiteController(ViewerRepositoryAsync<SiteUrl> repo)
        {
            _sitesRepo = repo;
        }

        [HttpPost]
        public async Task<ActionResult> Create(SiteUrl site)
        {
            if (!ModelState.IsValid)
            {
                return View("_ForPutAddress");
            }
            else
            {
                var sitesFromDb = _sitesRepo.GetAll().FirstOrDefault(s => s.Url == site.Url);

                if (sitesFromDb == null)
                {
                    await this.SetSiteToDB(site);
                }

                RedirectToAction("GetEntities", "Product", site.Url);
            }

            return null;
        }

        private async Task SetSiteToDB(SiteUrl site)
        {
            await _sitesRepo.CreateAsync(site);
        }

        [ChildActionOnly]
        public async Task ParsePageOnProducts(int siteID)
        {

        }

        [ChildActionOnly]
        public ActionResult _ForPutAddress()
        {
            return PartialView("_ForPutAddress");
        }

    }
}

InternetStoreViewer/Views/Site/_ForPutAddress.cshtml
@using InternetStoreViewer.Models
@model Site

<body>
    @using (Html.BeginForm("Create", "Site", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary(true)


        <div class="row">
            <div style="margin: 50px;" class="col-8">
                <span>
                    @Html.LabelFor(model => model.SiteUrl)
                </span>
                <span>
                    @Html.EditorFor(model => model.SiteUrl)
                    @Html.ValidationMessageFor(model => model.SiteUrl)
                </span>

            </div>
            <p>
                <input type="submit" value="Parsing" />

            </p>
        </div>
    }
</body>